Addhtml
soerendolling/website pull request #6
Opened 2021-03-04 17:55 UTC by soerendolling

I have created a html structer. Please review

2021-03-04 18:13 UTC, yvlange commented on index.html
> +  </body>
I love the positive energy!!

2021-03-04 18:17 UTC, hugh-burgess commented
verry nice!

2021-03-04 18:34 UTC, mpagels requested changes
Found some things in your code. Please review.
Very good job!

2021-03-04 18:34 UTC, mpagels commented on index.html
>      <title>Document</title>
Since this exercise is your personal website, try to name it like it. "Document" will show up in the tap for example. ;-)

2021-03-04 18:34 UTC, mpagels commented on index.html
> +    <h1 id="Top">Welcome to my super duper website</h2>
You using h1 at first and closing with h2. This is a mistake. use the closing h1 tag.

2021-03-04 18:34 UTC, mpagels commented on index.html
> +        <h3>Navigation</h2>
Please don't skip headings. First h1, then h2, then h3 and so on. Don't miss one. (You will learn later, how to display a different size for the heading)

2021-03-04 18:34 UTC, mpagels commented on index.html
> +                <li><a href=".edo">What else do i do</a></li>
The ".about" ,".ido" and ".edo" seems to be odd. Does this work?
If you want to "jump" to the corresponding section read for example [this](https://www.w3docs.com/snippets/html/how-to-create-an-anchor-link-to-jump-to-a-specific-part-of-a-page.html).

2021-03-04 18:38 UTC, mpagels commented
My comments seem a little harsh, now I read it again. This is not the case! Sorry if it comes across that way.

2021-03-05 09:11 UTC, closed without merging

2021-03-06 09:17 UTC, hugh-burgess commented on index.html
> -    <title>Document</title>
this is what appears in the tab of the browser, so you could call it 'Sören's website' or something! :)